name = "Osaka Jade"
version = "0.1.0"

authors = [
    "Ahum Maitra (@TheAhumMaitra) theahummaitra@gmail.com",
]

license = "MIT"
wallpapers_sources = ["https://github.com/basecamp/omarchy/blob/dev/themes/osaka-jade/backgrounds/"]
repo_url = "https://github.com/TheAhumMaitra/Osaka-Jade-For-Aurora"

[gtk]
theme_name = "Gruvbox-Material-Dark"
icon_theme = "Yaru-sage"

[vscode]
publisher = "jovejonovski"
extension_name = "ocean-green"
theme_name = "Ocean Green: Dark"

[zed]
theme_name = "Bamboo Multiplex"
