-- DO NOT EDIT THIS FILE
return {
  {
    "ribru17/bamboo.nvim",
    name = "bamboo",
    priority = 1000, -- make sure it loads first
    config = function()
      vim.cmd.colorscheme("bamboo")
    end,
  },
}

